### PR TITLE
use hex strings to be compatible with browser and cli

### PR DESCRIPTION
**Pull request by karissa**
but it makes the sharing box ugly..

screen shot 2016-09-09 at 4 58 32 pm

### CODE REVIEW

**Comment by juliangruber** [comment]
Is the problem here that dat-desktop uses the new encoding, or that browser and cli use the old one?

I'm down with using hex encoding for now, to ease the transition period, but I'm getting the feeling that the new encoding might not really happen, because of friction?

I'll look into styling this a bit better, maybe just putting it into a text box.

**Comment by karissa** [comment]
the cli uses hex strings, so i think we should tailor the desktop/browser to be the same @mafintosh

**Comment by karissa** [comment]
+1 on text box!

**Comment by karissa** [comment]
As far as internal/external, it makes sense to use the hex strings everywhere. 

I was under the impression that the encoding is useful for doing subdomains, but we decided to use hex strings as the defacto standard for now.

**Comment by juliangruber** [comment]
> but we decided to use hex strings as the defacto standard for now.

ah gotcha, I didn't get that. I'll deprecate dat-encoding then and go for hex strings all the way. Or do you think we should keep using a module for this, so it's easier to change things when necessary?

**Comment by karissa** [comment]
It would be nice if there was a module, but we do .toString('hex') everywhere including in the cli so it would be a bit of a project to migrate. Should at some point, though IMO.. :)

**Comment by juliangruber** [comment]
https://github.com/juliangruber/dat-encoding/pull/10

**Comment by karissa** [comment]
great

**Comment by karissa** [comment]
can we close this if you published dat-encoding?

**Comment by juliangruber** [comment]
not yet, i want to try to make this a non-breaking change

**Comment by juliangruber** [comment]
it did become a breaking change, but hopefully the last. i'm releasing now.

**Comment by juliangruber** [comment]
i have the release ready, just need to wait until i have faster wifi again. uploading currently times out.

**Pull request closed without merging**
