### PR TITLE
auth0 integration

### PR DESCRIPTION
**Pull request by juliangruber**
This is a WIP pull request.

The login fails currently although my details are correct, maybe there's something wrong with our api endpoint? You can just run this and it will immediately prompt you for credentials, so you can give it a try, @karissa

### CODE REVIEW

**Comment by karissa** [comment]
seems to be working for me, what were you trying to do? Did you try creating an account first?

**Comment by karissa** [comment]
Ah ok It seems that the bug is the popup is going blank the first time, then if you cancel and try again, it goes through the second time... no errors.

**Comment by karissa** [comment]
found the bug cross referenced here: https://github.com/auth0/auth0-electron/issues/16

**Comment by karissa** [comment]
looks like it works now with `sso: false`

**Comment by karissa** [comment]
ok updated the theme, too. 
screen shot 2016-10-17 at 6 57 49 pm

**Comment by clkao** [comment]
works great! we should probably have logout and a way to configure different client key based on dev/prod before this gets merged.

**Comment by karissa** [comment]
ok, added simple logout button but it needs to be actually designed. going to wait on choo for that.

I also added dev/prod environment stuff.

in the meantime i think we can merge.

**Pull request merged**
